import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { INSTALL_CAPTURE_SCRIPT } from "../lib/pwa";
import "./globals.css";
import "@xterm/xterm/css/xterm.css";

export const metadata: Metadata = {
  title: "APEX — Ghost In a Shell",
  description:
    "An open-source (MIT) animated orb + reasoning-graph UI. Hand-written SVG/CSS, no 3D libraries.",
  applicationName: "APEX",
  manifest: "/manifest.webmanifest",
  icons: {
    // A .ico is still what a browser tab asks for, and the PWA install checks
    // want a 192 and a 512. icon-*.png are generated by
    // scripts/generate-icons.mjs - re-run it rather than hand-editing them.
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/icon-32.png", type: "image/png", sizes: "32x32" },
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    title: "APEX",
    // black, not black-translucent: APEX fills the viewport and controls its own
    // background, and translucent would put the orb under the status bar with
    // no safe-area padding to keep it clear of a notch.
    statusBarStyle: "black",
  },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Lets the layout use env(safe-area-inset-*) on a notched device. See the
  // --safe-* custom properties in app/globals.css.
  viewportFit: "cover",
  themeColor: "#04080f",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Script
          id="apex-install-capture"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: INSTALL_CAPTURE_SCRIPT }}
        />
        {children}
      </body>
    </html>
  );
}